before_install:
  - gem update bundler
language: ruby
script: bundle exec rspec
rvm:
  - "1.8"
  - "1.9"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"
  - "2.4"
  - "2.5"
  - "2.6"
  - jruby-19mode
  - jruby-18mode
  - rubinius
